//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TAREA3Entities1 : DbContext
    {
        public TAREA3Entities1()
            : base("name=TAREA3Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Almacenes> Almacenes { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Stock> Stock { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
