//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class VLIS_Articulos
    {
        public int idArticulo { get; set; }
        public string Descripcion { get; set; }
        public string codigo { get; set; }
        public string Almacen { get; set; }
        public int Stock { get; set; }
        public int idAlmacen { get; set; }
    }
}
